version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27015:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network

  prolog-service:
    build:
      context: .
      dockerfile: Dockerfile.prolog
    ports:
      - "4244:4242"
    volumes:
      - ./pl:/app/pl
      - /mnt/hdd_2/abdu/prolog_out_v2:/mnt/prolog_out_v2
      - /mnt/hdd_2/abdu/prolog_out_v3:/mnt/prolog_out_v3
    networks:
      - app_network

  flask-app:
    build: .
    ports:
      - "5007:5000"
    environment:
      - FLASK_ENV=development
      - PREFECT_API_URL=http://prefect-service:4200/api
    volumes:
      - .:/app
    depends_on:
      - mongo
      - prolog-service
      - prefect-service
    command: >
      sh -c "
      python main.py --ensembl-hgnc-map data/ensembl_to_hgnc.pkl --hgnc-ensembl-map data/hgnc_to_ensembl.pkl \
      --go-map data/go_map.pkl --swipl-host prolog-service --swipl-port 4242 
      "
    networks:
      - app_network

  prefect-service:
    build:
      context: .
      dockerfile: Dockerfile.prefect
    ports:
      - "4202:4200"
    volumes:
      - .:/app
      - prefect-data:/root/.prefect 
    environment:
      - PREFECT_SERVER_PORT=4200
      - PREFECT_API_URL=http://prefect-service:4200/api
    env_file:
      - .env
    command: prefect server start --host 0.0.0.0
    networks:
      - app_network

volumes:
  mongo-data:
  prefect-data:

networks:
  app_network:
    driver: bridge