version: '3.8'

services:

  mongo:
    image: mongo:latest
    ports:
      - "27096:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network

  prolog-service:
    build:
      context: .
      dockerfile: Dockerfile.prolog
    ports:
      - "4291:4242"
    volumes:
      - ./pl:/app/pl
      - /mnt/hdd_1/tesnim/version1/prolog_out_v2:/mnt/prolog_out_v2
      - /mnt/hdd_1/tesnim/version1/prolog_out_v3:/mnt/prolog_out_v3
    networks:
      - app_network

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5098:5000"
    environment:
      - FLASK_ENV=development
      - PREFECT_API_URL=http://prefect-service:4200/api
      - OPENAI_API_KEY=${OpenAI}
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data:/app/data
      - /mnt/hdd_1/rediet/hypothesis-generation-demo/data:/app/data/external_data  
    depends_on:
      - mongo
      - prolog-service
      - prefect-service
    command: >
      sh -c "
      uv run python main.py --ensembl-hgnc-map data/ensembl_to_hgnc.pkl --hgnc-ensembl-map data/hgnc_to_ensembl.pkl \
      --go-map data/go_map.pkl --swipl-host prolog-service --swipl-port 4242 
      "
    networks:
      - app_network

  prefect-service:
    build:
      context: .
      dockerfile: Dockerfile.prefect
    ports:
      - "4292:4200"
    volumes:
      - .:/app
      - prefect-data:/root/.prefect 
    environment:
      - PREFECT_API_URL=http://localhost:4200/api
      - UV_PROJECT_ENVIRONMENT=/opt/prefect-venv
      - OPENAI_API_KEY=${OpenAI}
    env_file:
      - .env
    command: > 
      sh -c "uv run prefect server start --host 0.0.0.0"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
      interval: 30s
      timeout: 15s
      retries: 20
      start_period: 300s
  
  prefect-deployment:
    build:
      context: .
      dockerfile: Dockerfile.prefect
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c "
      uv run python deployments.py --ensembl-hgnc-map /app/data/ensembl_to_hgnc.pkl 
      --hgnc-ensembl-map /app/data/hgnc_to_ensembl.pkl 
      --go-map /app/data/go_map.pkl 
      --swipl-host prolog-service 
      --swipl-port 4242
      "
    environment:
    - PREFECT_API_URL=http://prefect-service:4200/api
    - UV_PROJECT_ENVIRONMENT=/opt/prefect-venv
    - OPENAI_API_KEY=${OpenAI}
    depends_on:
      prefect-service:
        condition: service_healthy
    networks:
      - app_network

volumes:
  mongo-data:
  prefect-data:

networks:
  app_network:
    driver: bridge